### ISSUE TITLE
Unknown resource type 'sequence' ,  Missing or invalid resource 'cameraMethod'

### ISSUE THREAD

**Issue by KnIfER** [LarsFlaeten/Proland_dev#1]
hellowold-core.exe:
```
INFO [UI] Status: Using GLEW 2.1.0

INFO [RESOURCE] Loading resource 'scene'
INFO [RESOURCE] Loaded file 'helloworld.xml'
INFO [RESOURCE] Loaded file 'helloworld.xml'
INFO [RESOURCE] Loading resource 'cameraMethod'
ERROR [RESOURCE] Unknown resource type 'sequence' at line 1 in <sequence name="cameraMethod">
    <foreach var="o" flag="dynamic" parallel="true">
        <callMethod name="$o.update" />
    </foreach>
    <foreach var="o" flag="object" culling="true">
        <callMethod name="$o.draw" />
    </foreach>
    <foreach var="o" flag="overlay">
        <callMethod name="$o.draw" />
    </foreach>
</sequence>

ERROR [RESOURCE] Missing or invalid resource 'cameraMethod'
ERROR [RESOURCE] Missing or invalid resource 'scene'
```

**Comment by LarsFlaeten** [comment]
Hi, it is a long time since I have been working on this code. On Linux builds this happens when you build the entire ork/proland lib as a static library, because the linker will not catch that the proland modules are invoked (since they are invoked as plugins in runtime by the xml settings file). The solution was either to build as shared (see compile option in cmake), og to force inclusion of the whole library ehwn using static linking. I have not tested ork/proland on windows.

**Comment by KnIfER** [comment]
have to compile both ork and proland as a dll

**Comment by cnDelbert** [comment]
@KnIfER 麻烦问下：

- 编译ork时，将ORK_API设置为dllexport，
- 编译proland时，ORK_API设置为dllimport，PROLAND_API设置为dllexport，
- 编译exe时，两者均为dllimport。

后面2 3两步怎样设置。

是examples中的设置和proland-开头的工程这只不同的macro吗？
